const responsesForRandomizedIndexes = [[
    "Hell yeah!",   
    "Absolutely, no doubt.",
    "No brainer.",
    "No shit, Sherlock.",
    "Bet your ass.",
    "Don't even trip, dog.",
    "You got that right.",
    "Fo' shizzle.",
    "Definitely, yo.",
    "Damn straight.",
    "The stars align for a yes.",
    "Can't argue with destiny.",
    "Fate says yes.",
    "Inevitable.",
    "It's written in the stars.",
    "You're on the money.",
    "That's a slam dunk.",
    "A foregone conclusion.",
    "Beyond a shadow of a doubt.",
    "It's a done deal."
  ],
  [
    "Nope, not a chance.",
    "Nah, I wouldn't count on it.",
    "Ain't happening.",
    "Sorry, not sorry.",
    "Not in this lifetime.",
    "Dream on.",
    "You wish.",
    "Fat chance.",
    "Hell to the no!",
    "Not even close.",
    "Don't hold your breath.",
    "Don't get your hopes up.",
    "The stars align for a no.",
    "Can't argue with no destiny.",
    "Fate says no.",
    "Inevitably no.",
    "The universe says no.",
    "That's a dead end.",
    "It's not looking good.",
    "It's a definite no."
  ]
];